name: code check

on: [push, pull_request]

jobs:

  gofmt:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check out source code
      uses: actions/checkout@v1

    - name: fmt
      run: d="$(gofmt -d ../../)" && if [ -n "$d" ]; then echo "Format error:" ; echo "$d"; exit 1; fi      


  checkcrd:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check out source code
      uses: actions/checkout@v1

    - name: recreate crd
      run: make manifests

    - name: check crd
      run: diff charts/mysql-operator/crds config/crd/bases
